Imported Upstream version 17.3-dfsg

diff --git a/lib/kernel/test/inet_res_SUITE_data/run-named b/lib/kernel/test/inet_res_SUITE_data/run-named
--- a/lib/kernel/test/inet_res_SUITE_data/run-named
+++ b/lib/kernel/test/inet_res_SUITE_data/run-named
@@ -2,7 +2,7 @@
 ##
 ## %CopyrightBegin%
 ## 
-## Copyright Ericsson AB 2009-2011. All Rights Reserved.
+## Copyright Ericsson AB 2009-2012. All Rights Reserved.
 ## 
 ## The contents of this file are subject to the Erlang Public License,
 ## Version 1.1, (the "License"); you may not use this file except in
@@ -71,10 +71,14 @@ test -d "$SRCDIR" || \
 test -f "$SRCDIR/$INC_FILE" || \
     error "Missing file: $SRCDIR/$INC_FILE !"
 
-# Locate named and check version
+# Locate named and check version.
+# The bind-named name is used for tricking Apparmor and such
+# by copying/hardlinking the real named to that name.
 NAMED=named
-for n in /usr/sbin/named /usr/sbin/in.named; do
-    test -x "$n" && NAMED="$n"
+for n in /usr/local/bin/bind-named /usr/local/bin/named \
+    /usr/sbin/bind-named /usr/sbin/named /usr/sbin/in.named
+do
+    test -x "$n" && NAMED="$n" && break
 done
 NAMED_VER="`"$NAMED" -v 2>&1`" || \
     error "Name server not found!"
@@ -151,13 +155,21 @@ echo "Cwd: `pwd`"
 echo "Nameserver: $NAMED_VER"
 echo "Port: $2"
 echo "ZoneDir: $3"
+echo "Command: $NAMED $NAMED_FG -c $CONF_FILE"
 $NAMED $NAMED_FG -c "$CONF_FILE" >"$LOG_FILE" 2>&1 </dev/null &
-NAMED=$!
-trap "kill -TERM $NAMED >/dev/null 2>&1; wait $NAMED >/dev/null 2>&1" \
+NAMED_PID=$!
+echo "Pid: $NAMED_PID"
+trap "kill $NAMED_PID >/dev/null 2>&1; wait $NAMED_PID >/dev/null 2>&1" \
     0 1 2 3 15
-sleep 2 # Give name server time to load its zone files
-echo "Running: Enter \`\`quit'' to terminate nameserver[$NAMED]..."
-while read LINE; do 
-    test :"$LINE" = :'quit' && break
-done
-echo "Closing: Terminating nameserver..."
+
+sleep 5 # Give name server time to load its zone files
+
+if ps -p $NAMED_PID >/dev/null 2>&1 || ps p $NAMED_PID >/dev/null 2>&1; then
+    echo "Running: Enter \`\`quit'' to terminate nameserver[$NAMED_PID]..."
+    while read LINE; do
+	test :"$LINE" = :'quit' && break
+    done
+    echo "Closing: Terminating nameserver..."
+else
+    error "$NAMED failed to start"
+fi
